<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>6 T-Test | Marketing Research Design &amp; Analysis 2019</title>
  <meta name="description" content="An Introduction to Statistics Using R" />
  <meta name="generator" content="bookdown 0.13 and GitBook 2.6.7" />

  <meta property="og:title" content="6 T-Test | Marketing Research Design &amp; Analysis 2019" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="An Introduction to Statistics Using R" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="6 T-Test | Marketing Research Design &amp; Analysis 2019" />
  
  <meta name="twitter:description" content="An Introduction to Statistics Using R" />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
<link rel="prev" href="correlation.html"/>
<link rel="next" href="anova.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<script src="libs/htmlwidgets-1.3/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.9.0/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.0.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.46.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.46.1/plotly-latest.min.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><strong><a href="./">MRDA 2019</a></strong></li>
<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome!</a></li>
<li class="chapter" data-level="" data-path="course-materials.html"><a href="course-materials.html"><i class="fa fa-check"></i>Course materials</a><ul>
<li class="chapter" data-level="" data-path="course-materials.html"><a href="course-materials.html#main-reference"><i class="fa fa-check"></i>Main reference</a></li>
<li class="chapter" data-level="" data-path="course-materials.html"><a href="course-materials.html#further-readings"><i class="fa fa-check"></i>Further readings</a></li>
<li class="chapter" data-level="" data-path="course-materials.html"><a href="course-materials.html#datacamp"><i class="fa fa-check"></i>DataCamp</a></li>
<li class="chapter" data-level="" data-path="course-materials.html"><a href="course-materials.html#other-web-resources"><i class="fa fa-check"></i>Other web-resources</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="getting-started.html"><a href="getting-started.html"><i class="fa fa-check"></i><b>1</b> Getting started</a><ul>
<li class="chapter" data-level="1.1" data-path="getting-started.html"><a href="getting-started.html#how-to-download-and-install-r-and-rstudio"><i class="fa fa-check"></i><b>1.1</b> How to download and install R and RStudio</a></li>
<li class="chapter" data-level="1.2" data-path="getting-started.html"><a href="getting-started.html#getting-help"><i class="fa fa-check"></i><b>1.2</b> Getting help</a></li>
<li class="chapter" data-level="1.3" data-path="getting-started.html"><a href="getting-started.html#functions"><i class="fa fa-check"></i><b>1.3</b> Functions</a></li>
<li class="chapter" data-level="1.4" data-path="getting-started.html"><a href="getting-started.html#packages"><i class="fa fa-check"></i><b>1.4</b> Packages</a></li>
<li class="chapter" data-level="1.5" data-path="getting-started.html"><a href="getting-started.html#a-typical-r-session"><i class="fa fa-check"></i><b>1.5</b> A typical R session</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="data-handling.html"><a href="data-handling.html"><i class="fa fa-check"></i><b>2</b> Data handling</a><ul>
<li class="chapter" data-level="2.1" data-path="data-handling.html"><a href="data-handling.html#basic-data-handling"><i class="fa fa-check"></i><b>2.1</b> Basic data handling</a><ul>
<li class="chapter" data-level="2.1.1" data-path="data-handling.html"><a href="data-handling.html#creating-objects"><i class="fa fa-check"></i><b>2.1.1</b> Creating objects</a></li>
<li class="chapter" data-level="2.1.2" data-path="data-handling.html"><a href="data-handling.html#data-types"><i class="fa fa-check"></i><b>2.1.2</b> Data types</a></li>
<li class="chapter" data-level="2.1.3" data-path="data-handling.html"><a href="data-handling.html#data-structures"><i class="fa fa-check"></i><b>2.1.3</b> Data structures</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="data-handling.html"><a href="data-handling.html#data-import-and-export"><i class="fa fa-check"></i><b>2.2</b> Data import and export</a><ul>
<li class="chapter" data-level="2.2.1" data-path="data-handling.html"><a href="data-handling.html#getting-data-for-this-course"><i class="fa fa-check"></i><b>2.2.1</b> Getting data for this course</a></li>
<li class="chapter" data-level="2.2.2" data-path="data-handling.html"><a href="data-handling.html#import-data-created-by-other-software-packages"><i class="fa fa-check"></i><b>2.2.2</b> Import data created by other software packages</a></li>
<li class="chapter" data-level="2.2.3" data-path="data-handling.html"><a href="data-handling.html#export-data"><i class="fa fa-check"></i><b>2.2.3</b> Export data</a></li>
<li class="chapter" data-level="2.2.4" data-path="data-handling.html"><a href="data-handling.html#import-data-from-the-web"><i class="fa fa-check"></i><b>2.2.4</b> Import data from the Web</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="data-handling.html"><a href="data-handling.html#summarizing-data"><i class="fa fa-check"></i><b>2.3</b> Summarizing data</a><ul>
<li class="chapter" data-level="2.3.1" data-path="data-handling.html"><a href="data-handling.html#summary-statistics"><i class="fa fa-check"></i><b>2.3.1</b> Summary statistics</a></li>
<li class="chapter" data-level="2.3.2" data-path="data-handling.html"><a href="data-handling.html#categorical-variables"><i class="fa fa-check"></i><b>2.3.2</b> Categorical variables</a></li>
<li class="chapter" data-level="2.3.3" data-path="data-handling.html"><a href="data-handling.html#continuous-variables"><i class="fa fa-check"></i><b>2.3.3</b> Continuous variables</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="data-handling.html"><a href="data-handling.html#data-visualization"><i class="fa fa-check"></i><b>2.4</b> Data visualization</a><ul>
<li class="chapter" data-level="2.4.1" data-path="data-handling.html"><a href="data-handling.html#categorical-variables-1"><i class="fa fa-check"></i><b>2.4.1</b> Categorical variables</a></li>
<li class="chapter" data-level="2.4.2" data-path="data-handling.html"><a href="data-handling.html#continuous-variables-1"><i class="fa fa-check"></i><b>2.4.2</b> Continuous variables</a></li>
<li class="chapter" data-level="2.4.3" data-path="data-handling.html"><a href="data-handling.html#saving-plots"><i class="fa fa-check"></i><b>2.4.3</b> Saving plots</a></li>
<li class="chapter" data-level="2.4.4" data-path="data-handling.html"><a href="data-handling.html#additional-options"><i class="fa fa-check"></i><b>2.4.4</b> Additional options</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="data-handling.html"><a href="data-handling.html#writing-reports-using-r-markdown"><i class="fa fa-check"></i><b>2.5</b> Writing reports using R-Markdown</a><ul>
<li class="chapter" data-level="2.5.1" data-path="data-handling.html"><a href="data-handling.html#creating-a-new-r-markdown-document"><i class="fa fa-check"></i><b>2.5.1</b> Creating a new R-Markdown document</a></li>
<li class="chapter" data-level="2.5.2" data-path="data-handling.html"><a href="data-handling.html#text-and-equations"><i class="fa fa-check"></i><b>2.5.2</b> Text and Equations</a></li>
<li class="chapter" data-level="2.5.3" data-path="data-handling.html"><a href="data-handling.html#r-code"><i class="fa fa-check"></i><b>2.5.3</b> R-Code</a></li>
<li class="chapter" data-level="2.5.4" data-path="data-handling.html"><a href="data-handling.html#latex-math"><i class="fa fa-check"></i><b>2.5.4</b> LaTeX Math</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="introduction-to-statistical-inference.html"><a href="introduction-to-statistical-inference.html"><i class="fa fa-check"></i><b>3</b> Introduction to Statistical Inference</a><ul>
<li class="chapter" data-level="3.1" data-path="introduction-to-statistical-inference.html"><a href="introduction-to-statistical-inference.html#if-we-knew-it-all"><i class="fa fa-check"></i><b>3.1</b> If we knew it all</a><ul>
<li class="chapter" data-level="3.1.1" data-path="introduction-to-statistical-inference.html"><a href="introduction-to-statistical-inference.html#sampling-from-a-known-population"><i class="fa fa-check"></i><b>3.1.1</b> Sampling from a known population</a></li>
<li class="chapter" data-level="3.1.2" data-path="introduction-to-statistical-inference.html"><a href="introduction-to-statistical-inference.html#standard-error-of-the-mean"><i class="fa fa-check"></i><b>3.1.2</b> Standard error of the mean</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="introduction-to-statistical-inference.html"><a href="introduction-to-statistical-inference.html#the-central-limit-theorem"><i class="fa fa-check"></i><b>3.2</b> The Central Limit Theorem</a></li>
<li class="chapter" data-level="3.3" data-path="introduction-to-statistical-inference.html"><a href="introduction-to-statistical-inference.html#using-what-we-actually-know"><i class="fa fa-check"></i><b>3.3</b> Using what we actually know</a><ul>
<li class="chapter" data-level="3.3.1" data-path="introduction-to-statistical-inference.html"><a href="introduction-to-statistical-inference.html#confidence-intervals-for-the-sample-mean"><i class="fa fa-check"></i><b>3.3.1</b> Confidence Intervals for the Sample Mean</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="introduction-to-statistical-inference.html"><a href="introduction-to-statistical-inference.html#summary"><i class="fa fa-check"></i><b>3.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html"><i class="fa fa-check"></i><b>4</b> Hypothesis testing</a><ul>
<li class="chapter" data-level="4.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#introduction"><i class="fa fa-check"></i><b>4.1</b> Introduction</a><ul>
<li class="chapter" data-level="4.1.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#the-null-hypothesis"><i class="fa fa-check"></i><b>4.1.1</b> The null hypothesis</a></li>
<li class="chapter" data-level="4.1.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#statistical-inference-on-a-sample"><i class="fa fa-check"></i><b>4.1.2</b> Statistical inference on a sample</a></li>
<li class="chapter" data-level="4.1.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#choosing-the-right-test"><i class="fa fa-check"></i><b>4.1.3</b> Choosing the right test</a></li>
<li class="chapter" data-level="4.1.4" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#summary-1"><i class="fa fa-check"></i><b>4.1.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#categorical-data"><i class="fa fa-check"></i><b>4.2</b> Categorical data</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="correlation.html"><a href="correlation.html"><i class="fa fa-check"></i><b>5</b> Correlation</a><ul>
<li class="chapter" data-level="5.1" data-path="correlation.html"><a href="correlation.html#correlation-coefficient"><i class="fa fa-check"></i><b>5.1</b> Correlation coefficient</a></li>
<li class="chapter" data-level="5.2" data-path="correlation.html"><a href="correlation.html#significance-testing"><i class="fa fa-check"></i><b>5.2</b> Significance testing</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="t-test.html"><a href="t-test.html"><i class="fa fa-check"></i><b>6</b> T-Test</a><ul>
<li class="chapter" data-level="6.1" data-path="t-test.html"><a href="t-test.html#one-sample-t-test"><i class="fa fa-check"></i><b>6.1</b> One sample t-test</a></li>
<li class="chapter" data-level="6.2" data-path="t-test.html"><a href="t-test.html#comparing-two-means"><i class="fa fa-check"></i><b>6.2</b> Comparing two means</a><ul>
<li class="chapter" data-level="6.2.1" data-path="t-test.html"><a href="t-test.html#independent-means-t-test"><i class="fa fa-check"></i><b>6.2.1</b> Independent-means t-test</a></li>
<li class="chapter" data-level="6.2.2" data-path="t-test.html"><a href="t-test.html#dependent-means-t-test"><i class="fa fa-check"></i><b>6.2.2</b> Dependent-means t-test</a></li>
<li class="chapter" data-level="6.2.3" data-path="t-test.html"><a href="t-test.html#further-considerations"><i class="fa fa-check"></i><b>6.2.3</b> Further considerations</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="anova.html"><a href="anova.html"><i class="fa fa-check"></i><b>7</b> ANOVA</a><ul>
<li class="chapter" data-level="7.1" data-path="anova.html"><a href="anova.html#introduction-1"><i class="fa fa-check"></i><b>7.1</b> Introduction</a></li>
<li class="chapter" data-level="7.2" data-path="anova.html"><a href="anova.html#decomposing-variance"><i class="fa fa-check"></i><b>7.2</b> Decomposing variance</a><ul>
<li class="chapter" data-level="7.2.1" data-path="anova.html"><a href="anova.html#total-sum-of-squares"><i class="fa fa-check"></i><b>7.2.1</b> Total sum of squares</a></li>
<li class="chapter" data-level="7.2.2" data-path="anova.html"><a href="anova.html#model-sum-of-squares"><i class="fa fa-check"></i><b>7.2.2</b> Model sum of squares</a></li>
<li class="chapter" data-level="7.2.3" data-path="anova.html"><a href="anova.html#residual-sum-of-squares"><i class="fa fa-check"></i><b>7.2.3</b> Residual sum of squares</a></li>
<li class="chapter" data-level="7.2.4" data-path="anova.html"><a href="anova.html#effect-strength"><i class="fa fa-check"></i><b>7.2.4</b> Effect strength</a></li>
<li class="chapter" data-level="7.2.5" data-path="anova.html"><a href="anova.html#test-of-significance"><i class="fa fa-check"></i><b>7.2.5</b> Test of significance</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="anova.html"><a href="anova.html#one-way-anova"><i class="fa fa-check"></i><b>7.3</b> One-way ANOVA</a><ul>
<li class="chapter" data-level="7.3.1" data-path="anova.html"><a href="anova.html#basic-anova"><i class="fa fa-check"></i><b>7.3.1</b> Basic ANOVA</a></li>
<li class="chapter" data-level="7.3.2" data-path="anova.html"><a href="anova.html#post-hoc-tests"><i class="fa fa-check"></i><b>7.3.2</b> Post-hoc tests</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>8</b> Regression</a><ul>
<li class="chapter" data-level="8.1" data-path="regression.html"><a href="regression.html#regression-1"><i class="fa fa-check"></i><b>8.1</b> Regression</a><ul>
<li class="chapter" data-level="8.1.1" data-path="regression.html"><a href="regression.html#simple-linear-regression"><i class="fa fa-check"></i><b>8.1.1</b> Simple linear regression</a></li>
<li class="chapter" data-level="8.1.2" data-path="regression.html"><a href="regression.html#multiple-linear-regression"><i class="fa fa-check"></i><b>8.1.2</b> Multiple linear regression</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="regression.html"><a href="regression.html#potential-problems"><i class="fa fa-check"></i><b>8.2</b> Potential problems</a><ul>
<li class="chapter" data-level="8.2.1" data-path="regression.html"><a href="regression.html#outliers"><i class="fa fa-check"></i><b>8.2.1</b> Outliers</a></li>
<li class="chapter" data-level="8.2.2" data-path="regression.html"><a href="regression.html#influential-observations"><i class="fa fa-check"></i><b>8.2.2</b> Influential observations</a></li>
<li class="chapter" data-level="8.2.3" data-path="regression.html"><a href="regression.html#non-linearity"><i class="fa fa-check"></i><b>8.2.3</b> Non-linearity</a></li>
<li class="chapter" data-level="8.2.4" data-path="regression.html"><a href="regression.html#non-constant-error-variance"><i class="fa fa-check"></i><b>8.2.4</b> Non-constant error variance</a></li>
<li class="chapter" data-level="8.2.5" data-path="regression.html"><a href="regression.html#non-normally-distributed-errors"><i class="fa fa-check"></i><b>8.2.5</b> Non-normally distributed errors</a></li>
<li class="chapter" data-level="8.2.6" data-path="regression.html"><a href="regression.html#correlation-of-errors"><i class="fa fa-check"></i><b>8.2.6</b> Correlation of errors</a></li>
<li class="chapter" data-level="8.2.7" data-path="regression.html"><a href="regression.html#collinearity"><i class="fa fa-check"></i><b>8.2.7</b> Collinearity</a></li>
<li class="chapter" data-level="8.2.8" data-path="regression.html"><a href="regression.html#omitted-variables"><i class="fa fa-check"></i><b>8.2.8</b> Omitted Variables</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="regression.html"><a href="regression.html#categorical-predictors"><i class="fa fa-check"></i><b>8.3</b> Categorical predictors</a><ul>
<li class="chapter" data-level="8.3.1" data-path="regression.html"><a href="regression.html#two-categories"><i class="fa fa-check"></i><b>8.3.1</b> Two categories</a></li>
<li class="chapter" data-level="8.3.2" data-path="regression.html"><a href="regression.html#more-than-two-categories"><i class="fa fa-check"></i><b>8.3.2</b> More than two categories</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Marketing Research Design &amp; Analysis 2019</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="t-test" class="section level1">
<h1><span class="header-section-number">6</span> T-Test</h1>
<div id="one-sample-t-test" class="section level2">
<h2><span class="header-section-number">6.1</span> One sample t-test</h2>
<p>The example we used in the introduction was an example of the <strong>one sample t-test</strong> and we computed all statistics by hand to explain the underlying intuition. When you conduct hypothesis tests using R, you do not need to calculate these statistics by hand, since there are build-in routines to conduct the steps for you. Let us use the same example again to see how you would conduct hypothesis tests in R.</p>
<p><strong>1. Formulate null and alternative hypotheses</strong></p>
<p>The null hypothesis states that there is no difference between the true population mean <span class="math inline">\(\mu\)</span> and the hypothesized value (i.e., <span class="math inline">\(10\)</span>), while the alternative hypothesis states the opposite:</p>
<p><span class="math display">\[
H_0: \mu = 10 \\
H_1: \mu \neq 10
\]</span></p>
<p><strong>2. Select an appropriate test</strong></p>
<p>Because we would like to test if the mean of a variable is different from a specified threshold, the one-sample t-test is appropriate. The assumptions of the test are 1) that the variable is measured using an interval or ratio scale, and 2) that the sampling distribution is normal. Both assumptions are met since 1) listening time is a ratio scale, and 2) we deem the sample size (n = 50) large enough to assume a normal sampling distribution according to the central limit theorem.</p>
<p><strong>3. Choose the level of significance</strong></p>
<p>We choose the conventional 5% significance level.</p>
<p><strong>4. Descriptive statistics and data visualization</strong></p>
<p>Provide descriptive statistics using the <code>stat.desc()</code> function:</p>
<div class="sourceCode" id="cb227"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb227-1" data-line-number="1"><span class="kw">library</span>(pastecs)</a>
<a class="sourceLine" id="cb227-2" data-line-number="2"><span class="kw">stat.desc</span>(student_sample)</a></code></pre></div>
<pre><code>##      nbr.val     nbr.null       nbr.na          min          max 
##   50.0000000    0.0000000    0.0000000    1.9365049   64.9843737 
##        range          sum       median         mean      SE.mean 
##   63.0478688  929.5971917   16.2246844   18.5919438    1.7744470 
## CI.mean.0.95          var      std.dev     coef.var 
##    3.5658848  157.4331152   12.5472354    0.6748749</code></pre>
<p>From this, we can already see that the mean is different from the hypothesized value. The question however remains, whether this difference is significantly different, given the sample size and the variability in the data. Since we only have one continuous variable, we can visualize the distribution in a histogram.</p>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb229-1" data-line-number="1"><span class="kw">ggplot</span>(<span class="kw">data.frame</span>(student_sample)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(<span class="dt">x =</span> student_sample), </a>
<a class="sourceLine" id="cb229-2" data-line-number="2">    <span class="dt">fill =</span> <span class="st">&quot;white&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">bins =</span> <span class="dv">20</span>) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb229-3" data-line-number="3"><span class="st">    </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Distribution of values in the sample&quot;</span>, </a>
<a class="sourceLine" id="cb229-4" data-line-number="4">        <span class="dt">x =</span> <span class="st">&quot;Hours&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Frequency&quot;</span>)</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-150-1.png" width="672" /></p>
<p><strong>5. Conduct significance test</strong></p>
<p>In the beginning of the chapter, we saw, how you could conduct significance test by hand. However, R has built-in routines that you can use to conduct the analyses. The <code>t.test()</code> function can be used to conduct the test. To test if the listening time among WU students was 10, you can use the following code:</p>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb230-1" data-line-number="1">H_<span class="dv">0</span> &lt;-<span class="st"> </span><span class="dv">10</span></a>
<a class="sourceLine" id="cb230-2" data-line-number="2"><span class="kw">t.test</span>(student_sample, <span class="dt">mu =</span> H_<span class="dv">0</span>, <span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)</a></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  student_sample
## t = 4.842, df = 49, p-value = 0.00001327
## alternative hypothesis: true mean is not equal to 10
## 95 percent confidence interval:
##  15.02606 22.15783
## sample estimates:
## mean of x 
##  18.59194</code></pre>
<p>Note that if you would have stated a directional hypothesis (i.e., the mean is either greater or smaller than 10 hours), you could easily amend the code to conduct a one sided test by changing the argument <code>alternative</code>from <code>'two.sided'</code> to either <code>'less'</code> or <code>'greater'</code>.</p>
<p><strong>6. Report results and draw a marketing conclusion</strong></p>
<p>Note that the results are the same as above, when we computed the test by hand. You could summarize the results as follows:</p>
<p>On average, the listening times in our sample were different form 10 hours per month (Mean = 18.99 hours, SE = 1.78). This difference was significant t(49) = 5.058, p &lt; .05 (95% CI = [15.42; 22.56]). Based on this evidence, we can conclude that the mean in our sample is significantly lower compared to the hypothesized population mean of <span class="math inline">\(10\)</span> hours, providing evidence against the null hypothesis.</p>
<p>Note that in the reporting above, the number <code>49</code> in parenthesis refers to the degrees of freedom that are available from the output.</p>
</div>
<div id="comparing-two-means" class="section level2">
<h2><span class="header-section-number">6.2</span> Comparing two means</h2>
<p>In the one-sample test above, we tested the hypothesis that the population mean has some specific value <span class="math inline">\(\mu_0\)</span> using data from only one sample. In marketing (as in many other disciplines), you will often be confronted with a situation where you wish to compare the means of two groups. For example, you may conduct an experiment and randomly split your sample into two groups, one of which receives a treatment (experimental group) while the other doesn’t (control group). In this case, the units (e.g., participants, products) in each group are different (‘between-subjects design’) and the samples are said to be independent. Hence, we would use a <strong>independent-means t-test</strong>. If you run an experiment with two experimental conditions and the same units (e.g., participants, products) were observed in both experimental conditions, the sample is said to be dependent in the sense that you have the same units in each group (‘within-subjects design’). In this case, we would need to conduct an <strong>dependent-means t-test</strong>. Both tests are described in the following sections, beginning with the independent-means t-test.</p>
<div id="independent-means-t-test" class="section level3">
<h3><span class="header-section-number">6.2.1</span> Independent-means t-test</h3>
<p>Using an independent-means t-test, we can compare the means of two possibly different populations. It is, for example, quite common for online companies to test new service features by running an experiment and randomly splitting their website visitors into two groups: one is exposed to the website with the new feature (experimental group) and the other group is not exposed to the new feature (control group). This is a typical A/B-Test scenario.</p>
<p>As an example, imagine that a music streaming service would like to introduce a new playlist feature that let’s their users access playlists created by other users. The goal is to analyse how the new service feature impacts the listening time of users. The service randomly splits a representative subset of their users into two groups and collects data about their listening times over one month. Let’s create a data set to simulate such a scenario.</p>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb232-1" data-line-number="1"><span class="kw">set.seed</span>(<span class="dv">321</span>)</a>
<a class="sourceLine" id="cb232-2" data-line-number="2">hours_population_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">rgamma</span>(<span class="dv">25000</span>, <span class="dt">shape =</span> <span class="dv">2</span>, <span class="dt">scale =</span> <span class="dv">10</span>)</a>
<a class="sourceLine" id="cb232-3" data-line-number="3"><span class="kw">set.seed</span>(<span class="dv">12567</span>)</a>
<a class="sourceLine" id="cb232-4" data-line-number="4">sample_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">25000</span>, <span class="dt">size =</span> <span class="dv">98</span>, <span class="dt">replace =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb232-5" data-line-number="5">sample_<span class="dv">1</span>_hours &lt;-<span class="st"> </span>hours_population_<span class="dv">1</span>[sample_<span class="dv">1</span>]</a>
<a class="sourceLine" id="cb232-6" data-line-number="6">sample_<span class="dv">1</span>_df &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">hours =</span> <span class="kw">round</span>(sample_<span class="dv">1</span>_hours, </a>
<a class="sourceLine" id="cb232-7" data-line-number="7">    <span class="dv">0</span>), <span class="dt">group =</span> <span class="st">&quot;A&quot;</span>)</a>
<a class="sourceLine" id="cb232-8" data-line-number="8"><span class="kw">set.seed</span>(<span class="dv">321</span>)</a>
<a class="sourceLine" id="cb232-9" data-line-number="9">hours_population_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">rgamma</span>(<span class="dv">25000</span>, <span class="dt">shape =</span> <span class="fl">2.5</span>, <span class="dt">scale =</span> <span class="dv">11</span>)</a>
<a class="sourceLine" id="cb232-10" data-line-number="10"><span class="kw">set.seed</span>(<span class="dv">12567</span>)</a>
<a class="sourceLine" id="cb232-11" data-line-number="11">sample_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">25000</span>, <span class="dt">size =</span> <span class="dv">112</span>, <span class="dt">replace =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb232-12" data-line-number="12">sample_<span class="dv">2</span>_hours &lt;-<span class="st"> </span>hours_population_<span class="dv">2</span>[sample_<span class="dv">2</span>]</a>
<a class="sourceLine" id="cb232-13" data-line-number="13">sample_<span class="dv">2</span>_df &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">hours =</span> <span class="kw">round</span>(sample_<span class="dv">2</span>_hours, </a>
<a class="sourceLine" id="cb232-14" data-line-number="14">    <span class="dv">0</span>), <span class="dt">group =</span> <span class="st">&quot;B&quot;</span>)</a>
<a class="sourceLine" id="cb232-15" data-line-number="15">hours_a_b &lt;-<span class="st"> </span><span class="kw">rbind</span>(sample_<span class="dv">1</span>_df, sample_<span class="dv">2</span>_df)</a>
<a class="sourceLine" id="cb232-16" data-line-number="16"><span class="kw">head</span>(hours_a_b)</a></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["hours"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["group"],"name":[2],"type":["fctr"],"align":["left"]}],"data":[{"1":"2","2":"A"},{"1":"27","2":"A"},{"1":"25","2":"A"},{"1":"2","2":"A"},{"1":"46","2":"A"},{"1":"13","2":"A"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>This data set contains two variables: the variable <code>hours</code> indicates the music listening times (in hours) and the variable <code>group</code> indicates from which group the observation comes, where ‘A’ refers to the control group (with the standard service) and ‘B’ refers to the experimental group (with the new playlist feature). Let’s first look at the descriptive statistics by group using the <code>describeBy</code> function:</p>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb233-1" data-line-number="1"><span class="kw">library</span>(psych)</a>
<a class="sourceLine" id="cb233-2" data-line-number="2"><span class="kw">describeBy</span>(hours_a_b<span class="op">$</span>hours, hours_a_b<span class="op">$</span>group)</a></code></pre></div>
<pre><code>## 
##  Descriptive statistics by group 
## group: A
##    vars  n  mean   sd median trimmed   mad min max range skew kurtosis
## X1    1 98 18.11 12.1     15   16.88 10.38   2  65    63 1.08     1.21
##      se
## X1 1.22
## -------------------------------------------------------- 
## group: B
##    vars   n mean    sd median trimmed   mad min max range skew kurtosis
## X1    1 112 28.5 17.97   24.5   26.56 15.57   1  83    82 0.96     0.82
##     se
## X1 1.7</code></pre>
<p>From this, we can already see that there is a difference in means between groups A and B. We can also see that the number of observations is different, as is the standard deviation. The question that we would like to answer is whether there is a significant difference in mean listening times between the groups. Remember that different users are contained in each group (‘between-subjects design’) and that the observations in one group are independent of the observations in the other group. Before we will see how you can easily conduct an independent-means t-test, let’s go over some theory first.</p>
<div id="theory" class="section level4">
<h4><span class="header-section-number">6.2.1.1</span> Theory</h4>
<p>As a starting point, let us label the unknown population mean of group A (control group) in our experiment <span class="math inline">\(\mu_1\)</span>, and that of group B (experimental group) <span class="math inline">\(\mu_2\)</span>. In this setting, the null hypothesis would state that the mean in group A is equal to the mean in group B:</p>
<p><span class="math display">\[
H_0: \mu_1=\mu_2
\]</span></p>
<p>This is equivalent to stating that the difference between the two groups (<span class="math inline">\(\delta\)</span>) is zero:</p>
<p><span class="math display">\[
H_0: \mu_1 - \mu_2=0=\delta
\]</span></p>
<p>That is, <span class="math inline">\(\delta\)</span> is the new unknown population parameter, so that the null and alternative hypothesis become:</p>
<p><span class="math display">\[
H_0: \delta = 0 \\
H_1: \delta \ne 0
\]</span></p>
<p>Remember that we usually don’t have access to the entire population so that we can not observe <span class="math inline">\(\delta\)</span> and have to estimate is from a sample statistic, which we define as <span class="math inline">\(d = \bar x_1-\bar x_2\)</span>, i.e., the difference between the sample means from group a (<span class="math inline">\(\bar x_1\)</span>) and group b (<span class="math inline">\(\bar x_2\)</span>). But can we really estimate <span class="math inline">\(d\)</span> from <span class="math inline">\(\delta\)</span>? Remember from the previous chapter, that we could estimate <span class="math inline">\(\mu\)</span> from <span class="math inline">\(\bar x\)</span>, because if we (hypothetically) take a larger number of samples, the distribution of the means of these samples (the sampling distribution) will be normally distributed and its mean will be (in the limit) equal to the population mean. It turns out that we can use the same underlying logic here. The above samples were drawn from two different populations with <span class="math inline">\(\mu_1\)</span> and <span class="math inline">\(\mu_2\)</span>. Let us compute the difference in means between these two populations:</p>
<div class="sourceCode" id="cb235"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb235-1" data-line-number="1">delta_pop &lt;-<span class="st"> </span><span class="kw">mean</span>(hours_population_<span class="dv">1</span>) <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(hours_population_<span class="dv">2</span>)</a>
<a class="sourceLine" id="cb235-2" data-line-number="2">delta_pop</a></code></pre></div>
<pre><code>## [1] -7.422855</code></pre>
<p>This means that the true difference between the mean listening times of groups a and b is -7.42. Let us now repeat the exercise from the previous chapter: let us repeatedly draw a large number of <span class="math inline">\(20,000\)</span> random samples of 100 users from each of these populations, compute the difference (i.e., <span class="math inline">\(d\)</span>, our estimate of <span class="math inline">\(\delta\)</span>), store the difference for each draw and create a histogram of <span class="math inline">\(d\)</span>.</p>
<div class="sourceCode" id="cb237"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb237-1" data-line-number="1"><span class="kw">set.seed</span>(<span class="dv">321</span>)</a>
<a class="sourceLine" id="cb237-2" data-line-number="2">hours_population_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">rgamma</span>(<span class="dv">25000</span>, <span class="dt">shape =</span> <span class="dv">2</span>, <span class="dt">scale =</span> <span class="dv">10</span>)</a>
<a class="sourceLine" id="cb237-3" data-line-number="3">hours_population_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">rgamma</span>(<span class="dv">25000</span>, <span class="dt">shape =</span> <span class="fl">2.5</span>, <span class="dt">scale =</span> <span class="dv">11</span>)</a>
<a class="sourceLine" id="cb237-4" data-line-number="4"></a>
<a class="sourceLine" id="cb237-5" data-line-number="5">samples &lt;-<span class="st"> </span><span class="dv">20000</span></a>
<a class="sourceLine" id="cb237-6" data-line-number="6">mean_delta &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="ot">NA</span>, <span class="dt">nrow =</span> samples)</a>
<a class="sourceLine" id="cb237-7" data-line-number="7"><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>samples) {</a>
<a class="sourceLine" id="cb237-8" data-line-number="8">    student_sample &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">25000</span>, <span class="dt">size =</span> <span class="dv">100</span>, <span class="dt">replace =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb237-9" data-line-number="9">    mean_delta[i, ] &lt;-<span class="st"> </span><span class="kw">mean</span>(hours_population_<span class="dv">1</span>[student_sample]) <span class="op">-</span><span class="st"> </span></a>
<a class="sourceLine" id="cb237-10" data-line-number="10"><span class="st">        </span><span class="kw">mean</span>(hours_population_<span class="dv">2</span>[student_sample])</a>
<a class="sourceLine" id="cb237-11" data-line-number="11">}</a>
<a class="sourceLine" id="cb237-12" data-line-number="12"></a>
<a class="sourceLine" id="cb237-13" data-line-number="13"><span class="kw">ggplot</span>(<span class="kw">data.frame</span>(mean_delta)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(<span class="dt">x =</span> mean_delta), </a>
<a class="sourceLine" id="cb237-14" data-line-number="14">    <span class="dt">bins =</span> <span class="dv">30</span>, <span class="dt">fill =</span> <span class="st">&quot;white&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb237-15" data-line-number="15"><span class="st">    </span><span class="kw">theme</span>(<span class="dt">legend.title =</span> <span class="kw">element_blank</span>()) <span class="op">+</span><span class="st"> </span><span class="kw">geom_vline</span>(<span class="kw">aes</span>(<span class="dt">xintercept =</span> <span class="kw">mean</span>(mean_delta)), </a>
<a class="sourceLine" id="cb237-16" data-line-number="16">    <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">+</span><span class="st"> </span><span class="kw">xlab</span>(<span class="st">&quot;d&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ggtitle</span>(<span class="kw">TeX</span>(<span class="kw">sprintf</span>(<span class="st">&quot;%d samples; $d_{</span><span class="ch">\\</span><span class="st">bar{x}}$ = %.2f&quot;</span>, </a>
<a class="sourceLine" id="cb237-17" data-line-number="17">    samples, <span class="kw">round</span>(<span class="kw">mean</span>(mean_delta), <span class="dv">2</span>))))</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-155-1.png" width="672" /></p>
<p>This gives us the sampling distribution of the mean differences between the samples. You will notice that this distribution follows a normal distribution and is centered around the true difference between the populations. This means that, on average, the difference between two sample means <span class="math inline">\(d\)</span> is a good estimate of <span class="math inline">\(\delta\)</span>. In our example, the difference between <span class="math inline">\(\bar x_1\)</span> and <span class="math inline">\(\bar x_2\)</span> is:</p>
<div class="sourceCode" id="cb238"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb238-1" data-line-number="1">mean_x1 &lt;-<span class="st"> </span><span class="kw">mean</span>(hours_a_b[hours_a_b<span class="op">$</span>group <span class="op">==</span><span class="st"> &quot;A&quot;</span>, <span class="st">&quot;hours&quot;</span>])</a>
<a class="sourceLine" id="cb238-2" data-line-number="2">mean_x1</a></code></pre></div>
<pre><code>## [1] 18.11224</code></pre>
<div class="sourceCode" id="cb240"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb240-1" data-line-number="1">mean_x2 &lt;-<span class="st"> </span><span class="kw">mean</span>(hours_a_b[hours_a_b<span class="op">$</span>group <span class="op">==</span><span class="st"> &quot;B&quot;</span>, <span class="st">&quot;hours&quot;</span>])</a>
<a class="sourceLine" id="cb240-2" data-line-number="2">mean_x2</a></code></pre></div>
<pre><code>## [1] 28.5</code></pre>
<div class="sourceCode" id="cb242"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb242-1" data-line-number="1">d &lt;-<span class="st"> </span>mean_x1 <span class="op">-</span><span class="st"> </span>mean_x2</a>
<a class="sourceLine" id="cb242-2" data-line-number="2">d</a></code></pre></div>
<pre><code>## [1] -10.38776</code></pre>
<p>Now that we have <span class="math inline">\(d\)</span> as an estimate of <span class="math inline">\(\delta\)</span>, how can we find out if the observed difference is significantly different from the null hypothesis (i.e., <span class="math inline">\(\delta = 0\)</span>)?</p>
<p>Recall from the previous section, that the standard deviation of the sampling distribution <span class="math inline">\(\sigma_{\bar x}\)</span> (i.e., the standard error) gives us indication about the precision of our estimate. Further recall that the standard error can be calculated as <span class="math inline">\(\sigma_{\bar x}={\sigma \over \sqrt{n}}\)</span>. So how can we calculate the standard error of the difference between two population means? According to the <strong>variance sum law</strong>, to find the variance of the sampling distribution of differences, we merely need to add together the variances of the sampling distributions of the two populations that we are comparing. To find the standard error, we only need to take the square root of the variance (because the standard error is the standard deviation of the sampling distribution and the standard deviation is the square root of the variance), so that we get:</p>
<p><span class="math display">\[
\sigma_{\bar x_1-\bar x_2} = \sqrt{{\sigma_1^2 \over n_1}+{\sigma_2^2 \over n_2}}
\]</span></p>
<p>But recall that we don’t actually know the true population standard deviation, so we use <span class="math inline">\(SE_{\bar x_1-\bar x_2}\)</span> as an estimate of <span class="math inline">\(\sigma_{\bar x_1-\bar x_2}\)</span>:</p>
<p><span class="math display">\[
SE_{\bar x_1-\bar x_2} = \sqrt{{s_1^2 \over n_1}+{s_2^2 \over n_2}}
\]</span></p>
<p>Hence, for our example, we can calculate the standard error as follows:</p>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb244-1" data-line-number="1">n1 &lt;-<span class="st"> </span><span class="dv">98</span></a>
<a class="sourceLine" id="cb244-2" data-line-number="2">n2 &lt;-<span class="st"> </span><span class="dv">112</span></a>
<a class="sourceLine" id="cb244-3" data-line-number="3">s1 &lt;-<span class="st"> </span><span class="kw">var</span>(hours_a_b[hours_a_b<span class="op">$</span>group <span class="op">==</span><span class="st"> &quot;A&quot;</span>, <span class="st">&quot;hours&quot;</span>])</a>
<a class="sourceLine" id="cb244-4" data-line-number="4">s1</a></code></pre></div>
<pre><code>## [1] 146.4924</code></pre>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb246-1" data-line-number="1">s2 &lt;-<span class="st"> </span><span class="kw">var</span>(hours_a_b[hours_a_b<span class="op">$</span>group <span class="op">==</span><span class="st"> &quot;B&quot;</span>, <span class="st">&quot;hours&quot;</span>])</a>
<a class="sourceLine" id="cb246-2" data-line-number="2">s2</a></code></pre></div>
<pre><code>## [1] 322.9189</code></pre>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb248-1" data-line-number="1">SE_x1_x2 &lt;-<span class="st"> </span><span class="kw">sqrt</span>(s1<span class="op">/</span>n1 <span class="op">+</span><span class="st"> </span>s2<span class="op">/</span>n2)</a>
<a class="sourceLine" id="cb248-2" data-line-number="2">SE_x1_x2</a></code></pre></div>
<pre><code>## [1] 2.092373</code></pre>
<p>Recall from above that we can calculate the t-statistic as:</p>
<p><span class="math display">\[
t= {\bar x - \mu_0 \over {s \over \sqrt{n}}} 
\]</span></p>
<p>Exchanging <span class="math inline">\(\bar x\)</span> for <span class="math inline">\(d\)</span>, we get</p>
<p><span class="math display">\[
t= {(\bar{x}_1 - \bar{x}_2) - (\mu_1 - \mu_2) \over {\sqrt{{s_1^2 \over n_1}+{s_2^2 \over n_2}}}} 
\]</span></p>
<p>Note that according to our hypothesis <span class="math inline">\(\mu_1-\mu_2=0\)</span>, so that we can calculate the t-statistic as:</p>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb250-1" data-line-number="1">t_score &lt;-<span class="st"> </span>d<span class="op">/</span>SE_x1_x2</a>
<a class="sourceLine" id="cb250-2" data-line-number="2">t_score</a></code></pre></div>
<pre><code>## [1] -4.964581</code></pre>
<p>Following the example of our one sample t-test above, we would now need to compare this calculated test statistic to a critical value in order to assess if <span class="math inline">\(d\)</span> is sufficiently far away from the null hypothesis to be statistically significant. To do this, we would need to know the exact t-distribution, which depends on the degrees of freedom. The problem is that deriving the degrees of freedom in this case is not that obvious. If we were willing to assume that <span class="math inline">\(\sigma_1=\sigma_2\)</span>, the correct t-distribution has <span class="math inline">\(n_1 -1 + n_2-1\)</span> degrees of freedom (i.e., the sum of the degrees of freedom of the two samples). However, because in real life we don not know if <span class="math inline">\(\sigma_1=\sigma_2\)</span>, we need to account for this additional uncertainty. We will not go into detail here, but R automatically uses a sophisticated approach to correct the degrees of freedom called the Welch’s correction, as we will see in the subsequent application.</p>
</div>
<div id="application" class="section level4">
<h4><span class="header-section-number">6.2.1.2</span> Application</h4>
<p>The section above explained the theory behind the independent-means t-test and showed how to compute the statistics manually. Obviously you don’t have to compute these statistics by hand in this section shows you how to conduct an independent-means t-test in R using the example from above.</p>
<p><strong>1. Formulate null and alternative hypotheses</strong></p>
<p>We wish to analyze whether there is a significant difference in music listening times between groups A and B. So our null hypothesis is that the means from the two populations are the same (i.e., there is no difference), while the alternative hypothesis states the opposite:</p>
<p><span class="math display">\[
H_0: \mu_1=\mu_2\\
H_1: \mu_1 \ne \mu_2
\]</span></p>
<p><strong>2. Select an appropriate test</strong></p>
<p>Since we have a ratio scaled variable (i.e., listening times) and two independent groups, where the mean of one sample is independent of the group of the second sample (i.e., the groups contain different units), the independent-means t-test is appropriate.</p>
<p><strong>3. Choose the level of significance</strong></p>
<p>We choose the conventional 5% significance level.</p>
<p><strong>4. Descriptive statistics and data visualization</strong></p>
<p>We can compute the descriptive statistics for each group separately, using the <code>describeBy()</code> function:</p>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb252-1" data-line-number="1"><span class="kw">library</span>(psych)</a>
<a class="sourceLine" id="cb252-2" data-line-number="2"><span class="kw">describeBy</span>(hours_a_b<span class="op">$</span>hours, hours_a_b<span class="op">$</span>group)</a></code></pre></div>
<pre><code>## 
##  Descriptive statistics by group 
## group: A
##    vars  n  mean   sd median trimmed   mad min max range skew kurtosis
## X1    1 98 18.11 12.1     15   16.88 10.38   2  65    63 1.08     1.21
##      se
## X1 1.22
## -------------------------------------------------------- 
## group: B
##    vars   n mean    sd median trimmed   mad min max range skew kurtosis
## X1    1 112 28.5 17.97   24.5   26.56 15.57   1  83    82 0.96     0.82
##     se
## X1 1.7</code></pre>
<p>This already shows us that the mean between groups A and B are different. We can visualize the data using a plot of means, boxplot, and a histogram.</p>
<div class="sourceCode" id="cb254"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb254-1" data-line-number="1"><span class="kw">ggplot</span>(hours_a_b, <span class="kw">aes</span>(group, hours)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_bar</span>(<span class="dt">stat =</span> <span class="st">&quot;summary&quot;</span>, </a>
<a class="sourceLine" id="cb254-2" data-line-number="2">    <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">fill =</span> <span class="st">&quot;white&quot;</span>, <span class="dt">width =</span> <span class="fl">0.7</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb254-3" data-line-number="3"><span class="st">    </span><span class="kw">geom_pointrange</span>(<span class="dt">stat =</span> <span class="st">&quot;summary&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Group&quot;</span>, </a>
<a class="sourceLine" id="cb254-4" data-line-number="4">    <span class="dt">y =</span> <span class="st">&quot;Listening time (hours)&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ggtitle</span>(<span class="st">&quot;Means and standard errors of listening times&quot;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb254-5" data-line-number="5"><span class="st">    </span><span class="kw">theme_bw</span>()</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-160-1.png" width="672" /></p>
<div class="sourceCode" id="cb255"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb255-1" data-line-number="1"><span class="kw">ggplot</span>(hours_a_b, <span class="kw">aes</span>(<span class="dt">x =</span> group, <span class="dt">y =</span> hours)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_boxplot</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb255-2" data-line-number="2"><span class="st">    </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Group&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Listening time (hours)&quot;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb255-3" data-line-number="3"><span class="st">    </span><span class="kw">ggtitle</span>(<span class="st">&quot;Boxplot of listening times&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>()</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-160-2.png" width="672" /></p>
<div class="sourceCode" id="cb256"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb256-1" data-line-number="1"><span class="kw">ggplot</span>(hours_a_b, <span class="kw">aes</span>(hours)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">col =</span> <span class="st">&quot;black&quot;</span>, </a>
<a class="sourceLine" id="cb256-2" data-line-number="2">    <span class="dt">fill =</span> <span class="st">&quot;darkblue&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Listening time (hours)&quot;</span>, </a>
<a class="sourceLine" id="cb256-3" data-line-number="3">    <span class="dt">y =</span> <span class="st">&quot;Frequency&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ggtitle</span>(<span class="st">&quot;Histogram of listening times&quot;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb256-4" data-line-number="4"><span class="st">    </span><span class="kw">facet_wrap</span>(<span class="op">~</span>group) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>()</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-160-3.png" width="672" /></p>
<p><strong>5. Conduct significance test</strong></p>
<p>To conduct the independent means t-test, we can use the <code>t.test()</code> function:</p>
<div class="sourceCode" id="cb257"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb257-1" data-line-number="1"><span class="kw">t.test</span>(hours <span class="op">~</span><span class="st"> </span>group, <span class="dt">data =</span> hours_a_b, <span class="dt">mu =</span> <span class="dv">0</span>, <span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>, </a>
<a class="sourceLine" id="cb257-2" data-line-number="2">    <span class="dt">conf.level =</span> <span class="fl">0.95</span>, <span class="dt">var.equal =</span> <span class="ot">FALSE</span>)</a></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  hours by group
## t = -4.9646, df = 195.73, p-value = 0.000001494
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -14.514246  -6.261264
## sample estimates:
## mean in group A mean in group B 
##        18.11224        28.50000</code></pre>
<p><strong>6. Report results and draw a marketing conclusion</strong></p>
<p>The results showed that listening times were higher in the experimental group (Mean = 26.43, SE = 1.54) compared to the control group (Mean = 20.91, SE = 1.37). This means that the listening times were 10.39 hours higher on average in the experimental group, compared to the control group. An independent-means t-test showed that this difference is significant t(207) = 2.684, p &lt; .05 (95% CI = [1.46,9.58]).</p>
</div>
</div>
<div id="dependent-means-t-test" class="section level3">
<h3><span class="header-section-number">6.2.2</span> Dependent-means t-test</h3>
<p>While the independent-means t-test is used when different units (e.g., participants, products) were assigned to the different condition, the <strong>dependent-means t-test</strong> is used when there are two experimental conditions and the same units (e.g., participants, products) were observed in both experimental conditions.</p>
<p>Imagine, for example, a slightly different experimental setup for the above experiment. Imagine that we do not assign different users to the groups, but that a sample of 100 users gets to use the music streaming service with the new feature for one month and we compare the music listening times of these users during the month of the experiment with the listening time in the previous month. Let us generate data for this example:</p>
<div class="sourceCode" id="cb259"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb259-1" data-line-number="1"><span class="kw">set.seed</span>(<span class="dv">321</span>)</a>
<a class="sourceLine" id="cb259-2" data-line-number="2">hours_population_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">rgamma</span>(<span class="dv">25000</span>, <span class="dt">shape =</span> <span class="dv">2</span>, <span class="dt">scale =</span> <span class="dv">10</span>)</a>
<a class="sourceLine" id="cb259-3" data-line-number="3"><span class="kw">set.seed</span>(<span class="dv">12567</span>)</a>
<a class="sourceLine" id="cb259-4" data-line-number="4">sample_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">25000</span>, <span class="dt">size =</span> <span class="dv">100</span>, <span class="dt">replace =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb259-5" data-line-number="5">sample_<span class="dv">1</span>_hours &lt;-<span class="st"> </span>hours_population_<span class="dv">1</span>[sample_<span class="dv">1</span>]</a>
<a class="sourceLine" id="cb259-6" data-line-number="6"><span class="kw">set.seed</span>(<span class="dv">321</span>)</a>
<a class="sourceLine" id="cb259-7" data-line-number="7">hours_population_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">rgamma</span>(<span class="dv">25000</span>, <span class="dt">shape =</span> <span class="fl">2.5</span>, <span class="dt">scale =</span> <span class="dv">11</span>)</a>
<a class="sourceLine" id="cb259-8" data-line-number="8"><span class="kw">set.seed</span>(<span class="dv">12567</span>)</a>
<a class="sourceLine" id="cb259-9" data-line-number="9">sample_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">25000</span>, <span class="dt">size =</span> <span class="dv">100</span>, <span class="dt">replace =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb259-10" data-line-number="10">sample_<span class="dv">2</span>_hours &lt;-<span class="st"> </span>hours_population_<span class="dv">2</span>[sample_<span class="dv">2</span>]</a>
<a class="sourceLine" id="cb259-11" data-line-number="11">hours_a_b_paired &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">hours_a =</span> <span class="kw">round</span>(sample_<span class="dv">1</span>_hours, </a>
<a class="sourceLine" id="cb259-12" data-line-number="12">    <span class="dv">0</span>), <span class="dt">hours_b =</span> <span class="kw">round</span>(sample_<span class="dv">2</span>_hours, <span class="dv">0</span>))</a>
<a class="sourceLine" id="cb259-13" data-line-number="13"><span class="kw">head</span>(hours_a_b_paired)</a></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["hours_a"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["hours_b"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"2","2":"24"},{"1":"27","2":"21"},{"1":"25","2":"51"},{"1":"2","2":"12"},{"1":"46","2":"54"},{"1":"13","2":"18"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>Note that the data set has almost the same structure as before only that we know have two variables representing the listening times of each user in the month before the experiment and during the month of the experiment when the new feature was tested.</p>
<div id="theory-1" class="section level4">
<h4><span class="header-section-number">6.2.2.1</span> Theory</h4>
<p>In this case, we want to test the hypothesis that there is no difference in mean the mean listening times between the two months. This can be expressed as follows:</p>
<p><span class="math display">\[
H_0: \mu_D = 0 \\
\]</span>
Note that the hypothesis only refers to one population, since both observations come from the same units (i.e., users). To use consistent notation, we replace <span class="math inline">\(\mu_D\)</span> with <span class="math inline">\(\delta\)</span> and get:</p>
<p><span class="math display">\[
H_0: \delta = 0 \\
H_1: \delta \neq 0
\]</span></p>
<p>where <span class="math inline">\(\delta\)</span> denotes the difference between the observed listening times from the two consecutive months <strong>of the same users</strong>. As is the previous example, since we do not observe the entire population, we estimate <span class="math inline">\(\delta\)</span> based on the sample using <span class="math inline">\(d\)</span>, which is the difference in mean listening time between the two months for our sample. Note that we assume that everything else (e.g., number of new releases) remained constant over the two month to keep it simple. We can show as above that the sampling distribution follows a normal distribution with a mean that is (in the limit) the same as the population mean. This means, again, that the difference in sample means is a good estimate for the difference in population means. Let’s compute a new variable <span class="math inline">\(d\)</span>, which is the difference between two month.</p>
<div class="sourceCode" id="cb260"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb260-1" data-line-number="1">hours_a_b_paired<span class="op">$</span>d &lt;-<span class="st"> </span>hours_a_b_paired<span class="op">$</span>hours_a <span class="op">-</span><span class="st"> </span>hours_a_b_paired<span class="op">$</span>hours_b</a>
<a class="sourceLine" id="cb260-2" data-line-number="2"><span class="kw">head</span>(hours_a_b_paired)</a></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["hours_a"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["hours_b"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["d"],"name":[3],"type":["dbl"],"align":["right"]}],"data":[{"1":"2","2":"24","3":"-22"},{"1":"27","2":"21","3":"6"},{"1":"25","2":"51","3":"-26"},{"1":"2","2":"12","3":"-10"},{"1":"46","2":"54","3":"-8"},{"1":"13","2":"18","3":"-5"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>Note that we now have a new variable, which is the difference in listening times (in hours) between the two months. The mean of this difference is:</p>
<div class="sourceCode" id="cb261"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb261-1" data-line-number="1">mean_d &lt;-<span class="st"> </span><span class="kw">mean</span>(hours_a_b_paired<span class="op">$</span>d)</a>
<a class="sourceLine" id="cb261-2" data-line-number="2">mean_d</a></code></pre></div>
<pre><code>## [1] -11.65</code></pre>
<p>Again, we use <span class="math inline">\(SE_{\bar x}\)</span> as an estimate of <span class="math inline">\(\sigma_{\bar x}\)</span>:</p>
<p><span class="math display">\[
SE_{\bar d}={s \over \sqrt{n}}
\]</span>
Hence, we can compute the standard error as:</p>
<div class="sourceCode" id="cb263"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb263-1" data-line-number="1">n &lt;-<span class="st"> </span><span class="kw">nrow</span>(hours_a_b_paired)</a>
<a class="sourceLine" id="cb263-2" data-line-number="2">SE_d &lt;-<span class="st"> </span><span class="kw">sd</span>(hours_a_b_paired<span class="op">$</span>d)<span class="op">/</span><span class="kw">sqrt</span>(n)</a>
<a class="sourceLine" id="cb263-3" data-line-number="3">SE_d</a></code></pre></div>
<pre><code>## [1] 2.151503</code></pre>
<p>The test statistic is therefore:</p>
<p><span class="math display">\[
t = {\bar d-  \mu_0 \over SE_{\bar d}}
\]</span>
on 99 (i.e., n-1) degrees of freedom. Now we can compute the t-statistic as follows:</p>
<div class="sourceCode" id="cb265"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb265-1" data-line-number="1">t_score &lt;-<span class="st"> </span>mean_d<span class="op">/</span>SE_d</a>
<a class="sourceLine" id="cb265-2" data-line-number="2">t_score</a></code></pre></div>
<pre><code>## [1] -5.41482</code></pre>
<div class="sourceCode" id="cb267"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb267-1" data-line-number="1"><span class="kw">qt</span>(<span class="fl">0.975</span>, <span class="dt">df =</span> <span class="dv">99</span>)</a></code></pre></div>
<pre><code>## [1] 1.984217</code></pre>
<p>Note that in the case of the dependent-means t-test, we only base our hypothesis on one population and hence there is only one population variance. This is because in the dependent sample test, the observations come from the same observational units (i.e., users). Hence, there is no unsystematic variation due to potential differences between users that were assigned to the experimental groups. This means that the influence of unobserved factors (unsystematic variation) relative to the variation due to the experimental manipulation (systematic variation) is not as strong in the dependent-means test compared to the independent-means test and we don’t need to correct for differences in the population variances.</p>
</div>
<div id="application-1" class="section level4">
<h4><span class="header-section-number">6.2.2.2</span> Application</h4>
<p>Again, we don’t have to compute all this by hand since the <code>t.test(...)</code> function can be used to do it for us. Now we have to use the argument <code>paired=TRUE</code> to let R know that we are working with dependent observations.</p>
<p><strong>1. Formulate null and alternative hypotheses</strong></p>
<p>We would like to the test if there is a difference in music listening times between the two consecutive months, so our null hypothesis is that there is no difference, while the alternative hypothesis states the opposite:</p>
<p><span class="math display">\[
H_0: \mu_D = 0 \\
H_0: \mu_D \ne 0
\]</span></p>
<p><strong>2. Select an appropriate test</strong></p>
<p>Since we have a ratio scaled variable (i.e., listening times) and two observations of the same group of users (i.e., the groups contain the same units), the dependent-means t-test is appropriate.</p>
<p><strong>3. Choose the level of significance</strong></p>
<p>We choose the conventional 5% significance level.</p>
<p><strong>4. Descriptive statistics and data visualization</strong></p>
<p>We can compute the descriptive statistics for each month separately, using the <code>describe()</code> function:</p>
<div class="sourceCode" id="cb269"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb269-1" data-line-number="1"><span class="kw">library</span>(psych)</a>
<a class="sourceLine" id="cb269-2" data-line-number="2"><span class="kw">describe</span>(hours_a_b_paired)</a></code></pre></div>
<pre><code>## hours_a_b_paired 
## 
##  3  Variables      100  Observations
## ---------------------------------------------------------------------------
## hours_a 
##        n  missing distinct     Info     Mean      Gmd      .05      .10 
##      100        0       38    0.998    17.93    13.16     3.00     5.90 
##      .25      .50      .75      .90      .95 
##     8.00    15.00    25.25    34.30    39.05 
## 
## lowest :  2  3  4  5  6, highest: 40 41 46 50 65
## ---------------------------------------------------------------------------
## hours_b 
##        n  missing distinct     Info     Mean      Gmd      .05      .10 
##      100        0       48    0.999    29.58     20.3     5.95     8.00 
##      .25      .50      .75      .90      .95 
##    15.75    25.00    40.00    54.20    63.30 
## 
## lowest :  3  4  5  6  8, highest: 63 69 78 81 83
## ---------------------------------------------------------------------------
## d 
##        n  missing distinct     Info     Mean      Gmd      .05      .10 
##      100        0       52    0.999   -11.65    23.75   -54.15   -35.20 
##      .25      .50      .75      .90      .95 
##   -23.25    -9.00     2.00    12.00    21.05 
## 
## lowest : -76 -64 -63 -60 -57, highest:  22  23  24  34  51
## ---------------------------------------------------------------------------</code></pre>
<p>This already shows us that the mean between the two months are different. We can visiualize the data using a plot of means, boxplot, and a histogram.</p>
<p>To plot the data, we need to do some restructuring first, since the variables are now stored in two different columns (“hours_a” and “hours_b”). This is also known as the “wide” format. To plot the data we need all observations to be stored in one variable. This is also known as the “long” format. We can use the <code>melt(...)</code> function from the <code>reshape2</code>package to “melt” the two variable into one column to plot the data.</p>
<div class="sourceCode" id="cb271"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb271-1" data-line-number="1"><span class="kw">library</span>(reshape2)</a>
<a class="sourceLine" id="cb271-2" data-line-number="2">hours_a_b_paired_long &lt;-<span class="st"> </span><span class="kw">melt</span>(hours_a_b_paired[, <span class="kw">c</span>(<span class="st">&quot;hours_a&quot;</span>, </a>
<a class="sourceLine" id="cb271-3" data-line-number="3">    <span class="st">&quot;hours_b&quot;</span>)])</a>
<a class="sourceLine" id="cb271-4" data-line-number="4"><span class="kw">names</span>(hours_a_b_paired_long) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;group&quot;</span>, <span class="st">&quot;hours&quot;</span>)</a>
<a class="sourceLine" id="cb271-5" data-line-number="5"><span class="kw">head</span>(hours_a_b_paired_long)</a></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["group"],"name":[1],"type":["fctr"],"align":["left"]},{"label":["hours"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"hours_a","2":"2"},{"1":"hours_a","2":"27"},{"1":"hours_a","2":"25"},{"1":"hours_a","2":"2"},{"1":"hours_a","2":"46"},{"1":"hours_a","2":"13"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>Now we are ready to plot the data:</p>
<div class="sourceCode" id="cb272"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb272-1" data-line-number="1"><span class="kw">ggplot</span>(hours_a_b_paired_long, <span class="kw">aes</span>(group, hours)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb272-2" data-line-number="2"><span class="st">    </span><span class="kw">geom_bar</span>(<span class="dt">stat =</span> <span class="st">&quot;summary&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">fill =</span> <span class="st">&quot;white&quot;</span>, </a>
<a class="sourceLine" id="cb272-3" data-line-number="3">        <span class="dt">width =</span> <span class="fl">0.7</span>) <span class="op">+</span><span class="st"> </span><span class="kw">geom_pointrange</span>(<span class="dt">stat =</span> <span class="st">&quot;summary&quot;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb272-4" data-line-number="4"><span class="st">    </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Group&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Listening time (hours)&quot;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb272-5" data-line-number="5"><span class="st">    </span><span class="kw">ggtitle</span>(<span class="st">&quot;Means and standard errors of listining times&quot;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb272-6" data-line-number="6"><span class="st">    </span><span class="kw">theme_bw</span>()</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-169-1.png" width="672" /></p>
<div class="sourceCode" id="cb273"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb273-1" data-line-number="1"><span class="kw">ggplot</span>(hours_a_b_paired_long, <span class="kw">aes</span>(<span class="dt">x =</span> group, <span class="dt">y =</span> hours)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb273-2" data-line-number="2"><span class="st">    </span><span class="kw">geom_boxplot</span>() <span class="op">+</span><span class="st"> </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Group&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Listening time (hours)&quot;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb273-3" data-line-number="3"><span class="st">    </span><span class="kw">ggtitle</span>(<span class="st">&quot;Boxplot of listening times&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>()</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-169-2.png" width="672" /></p>
<div class="sourceCode" id="cb274"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb274-1" data-line-number="1"><span class="kw">ggplot</span>(hours_a_b_paired_long, <span class="kw">aes</span>(hours)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">col =</span> <span class="st">&quot;black&quot;</span>, </a>
<a class="sourceLine" id="cb274-2" data-line-number="2">    <span class="dt">fill =</span> <span class="st">&quot;darkblue&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Listening time (hours)&quot;</span>, </a>
<a class="sourceLine" id="cb274-3" data-line-number="3">    <span class="dt">y =</span> <span class="st">&quot;Frequency&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ggtitle</span>(<span class="st">&quot;Histogram of listening times&quot;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb274-4" data-line-number="4"><span class="st">    </span><span class="kw">facet_wrap</span>(<span class="op">~</span>group) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>()</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-169-3.png" width="672" /></p>
<p><strong>5. Conduct significance test</strong></p>
<p>To conduct the independent means t-test, we can use the <code>t.test()</code> function with the argument <code>paired = TRUE</code>:</p>
<div class="sourceCode" id="cb275"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb275-1" data-line-number="1"><span class="kw">t.test</span>(hours_a_b_paired<span class="op">$</span>hours_a, hours_a_b_paired<span class="op">$</span>hours_b, </a>
<a class="sourceLine" id="cb275-2" data-line-number="2">    <span class="dt">mu =</span> <span class="dv">0</span>, <span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>, <span class="dt">conf.level =</span> <span class="fl">0.95</span>, </a>
<a class="sourceLine" id="cb275-3" data-line-number="3">    <span class="dt">paired =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  hours_a_b_paired$hours_a and hours_a_b_paired$hours_b
## t = -5.4148, df = 99, p-value = 0.00000043
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -15.919048  -7.380952
## sample estimates:
## mean of the differences 
##                  -11.65</code></pre>
<p><strong>6. Report results and draw a marketing conclusion</strong></p>
<p>On average, the same users used the service more when it included the new feature (M = 25.96, SE = 1.68) compared to the service without the feature (M = 20.99, SE = 1.34). This difference was significant t(99) = 2.3781, p &lt; .05 (95% CI = [0.82, 9.12]).</p>
</div>
</div>
<div id="further-considerations" class="section level3">
<h3><span class="header-section-number">6.2.3</span> Further considerations</h3>
<div id="type-i-and-type-ii-errors" class="section level4">
<h4><span class="header-section-number">6.2.3.1</span> Type I and Type II Errors</h4>
<p>When choosing the level of significance (<span class="math inline">\(\alpha\)</span>). It is important to note that the choice of the significance level affects the type 1 and type 2 error:</p>
<ul>
<li>Type I error: When we believe there is a genuine effect in our population, when in fact there isn’t. Probability of type I error (<span class="math inline">\(\alpha\)</span>) = level of significance.</li>
<li>Type II error: When we believe that there is no effect in the population, when in fact there is.</li>
</ul>
<p>This following table shows the possible outcomes of a test (retain vs. reject <span class="math inline">\(H_0\)</span>), depending on whether <span class="math inline">\(H_0\)</span> is true or false in reality.</p>
<table>
<colgroup>
<col width="16%" />
<col width="41%" />
<col width="41%" />
</colgroup>
<thead>
<tr class="header">
<th> </th>
<th>Retain <b>H<sub>0</sub></b></th>
<th>Reject <b>H<sub>0</sub></b></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><b>H<sub>0</sub> is true</b></td>
<td>Correct decision:<br>1-α (probability of correct retention);</td>
<td>Type 1 error:<br> α (level of significance)</td>
</tr>
<tr class="even">
<td><b>H<sub>0</sub> is false</b></td>
<td>Type 2 error:<br>β (type 2 error rate)</td>
<td>Correct decision:<br>1-β (power of the test)</td>
</tr>
</tbody>
</table>
</div>
<div id="significance-level-sample-size-power-and-effect-size" class="section level4">
<h4><span class="header-section-number">6.2.3.2</span> Significance level, sample size, power, and effect size</h4>
<p>When you plan to conduct an experiment, there are some factors that are under direct control of the researcher:</p>
<ul>
<li><strong>Significance level (<span class="math inline">\(\alpha\)</span>)</strong>: The probability of finding an effect that does not genuinely exist.</li>
<li><strong>Sample size (n)</strong>: The number of observations in each group of the experimental design.</li>
</ul>
<p>Unlike α and n, which are specified by the researcher, the magnitude of β depends on the actual value of the population parameter. In addition, β is influenced by the effect size (e.g., Cohen’s d), which can be used to determine a standardized measure of the magnitude of an observed effect. The following parameters are affected more indirectly:</p>
<ul>
<li><strong>Power (1-β)</strong>: The probability of finding an effect that does genuinely exists.</li>
<li><strong>Effect size (d)</strong>: Standardized measure of the effect size under the alternate hypothesis.</li>
</ul>
<p>Although β is unknown, it is related to α. For example, if we would like to be absolutely sure that we do not falsely identify an effect which does not exist (i.e., make a type I error), this means that the probability of identifying an effect that does exist (i.e., 1-β) decreases and vice versa. Thus, an extremely low value of α (e.g., α = 0.0001) will result in intolerably high β errors. A common approach is to set α=0.05 and β=0.80.</p>
<p>Unlike the t-value of our test, the effect size (d) is unaffected by the sample size and can be categorized as follows (see Cohen, J. 1988):</p>
<ul>
<li>0.2 (small effect)</li>
<li>0.5 (medium effect)</li>
<li>0.8 (large effect)</li>
</ul>
<p>In order to test more subtle effects (smaller effect sizes), you need a larger sample size compared to the test of more obvious effects. In <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2205186" target="_blank">this paper</a>, you can find a list of examples for different effect sizes and the number of observations you need to reliably find an effect of that magnitude. Although the exact effect size is unknown before the experiment, you might be able to make a guess about the effect size (e.g., based on previous studies).</p>
<p>If you wish to obtain a standardized measure of the effect, you may compute the effect size (Cohen’s d) using the <code>cohensD()</code> function from the <code>lsr</code> package. Using the examples from the independent-means t-test above, we would use:</p>
<div class="sourceCode" id="cb277"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb277-1" data-line-number="1"><span class="kw">library</span>(lsr)</a>
<a class="sourceLine" id="cb277-2" data-line-number="2"><span class="kw">cohensD</span>(hours <span class="op">~</span><span class="st"> </span>group, <span class="dt">data =</span> hours_a_b)</a></code></pre></div>
<pre><code>## [1] 0.6696301</code></pre>
<p>According to the thresholds defined above, this effect would be judged to be a small-medium effect.</p>
<p>For the dependent-means t-test, we would use:</p>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb279-1" data-line-number="1"><span class="kw">cohensD</span>(hours_a_b_paired<span class="op">$</span>hours_a, hours_a_b_paired<span class="op">$</span>hours_b, </a>
<a class="sourceLine" id="cb279-2" data-line-number="2">    <span class="dt">method =</span> <span class="st">&quot;paired&quot;</span>)</a></code></pre></div>
<pre><code>## [1] 0.541482</code></pre>
<p>According to the thresholds defined above, this effect would also be judged to be a small-medium effect.</p>
<p>When constructing an experimental design, your goal should be to maximize the power of the test while maintaining an acceptable significance level and keeping the sample as small as possible. To achieve this goal, you may use the <code>pwr</code> package, which let’s you compute <code>n</code>, <code>d</code>, <code>alpha</code>, and <code>power</code>. You only need to specify three of the four input variables to get the fourth.</p>
<p>For example, what sample size do we need (per group) to identify an effect with d = 0.6, α = 0.05, and power = 0.8:</p>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb281-1" data-line-number="1"><span class="kw">library</span>(pwr)</a>
<a class="sourceLine" id="cb281-2" data-line-number="2"><span class="kw">pwr.t.test</span>(<span class="dt">d =</span> <span class="fl">0.6</span>, <span class="dt">sig.level =</span> <span class="fl">0.05</span>, <span class="dt">power =</span> <span class="fl">0.8</span>, </a>
<a class="sourceLine" id="cb281-3" data-line-number="3">    <span class="dt">type =</span> <span class="kw">c</span>(<span class="st">&quot;two.sample&quot;</span>), <span class="dt">alternative =</span> <span class="kw">c</span>(<span class="st">&quot;two.sided&quot;</span>))</a></code></pre></div>
<pre><code>## 
##      Two-sample t test power calculation 
## 
##               n = 44.58577
##               d = 0.6
##       sig.level = 0.05
##           power = 0.8
##     alternative = two.sided
## 
## NOTE: n is number in *each* group</code></pre>
<p>Or we could ask, what is the power of our test with 51 observations in each group, d = 0.6, and α = 0.05:</p>
<div class="sourceCode" id="cb283"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb283-1" data-line-number="1"><span class="kw">pwr.t.test</span>(<span class="dt">n =</span> <span class="dv">51</span>, <span class="dt">d =</span> <span class="fl">0.6</span>, <span class="dt">sig.level =</span> <span class="fl">0.05</span>, <span class="dt">type =</span> <span class="kw">c</span>(<span class="st">&quot;two.sample&quot;</span>), </a>
<a class="sourceLine" id="cb283-2" data-line-number="2">    <span class="dt">alternative =</span> <span class="kw">c</span>(<span class="st">&quot;two.sided&quot;</span>))</a></code></pre></div>
<pre><code>## 
##      Two-sample t test power calculation 
## 
##               n = 51
##               d = 0.6
##       sig.level = 0.05
##           power = 0.850985
##     alternative = two.sided
## 
## NOTE: n is number in *each* group</code></pre>
</div>
<div id="p-values-stopping-rules-and-p-hacking" class="section level4">
<h4><span class="header-section-number">6.2.3.3</span> P-values, stopping rules and p-hacking</h4>
<p>From my experience, students tend to place a lot of weight on p-values when interpreting their research findings. It is therefore important to note some points that hopefully help to put the meaning of a “significant” vs. “insignificant” test result into perspective.</p>
<p><strong>Significant result</strong></p>
<ul>
<li>Even if the probability of the effect being a chance result is small (e.g., less than .05) it doesn’t necessarily mean that the effect is important.</li>
<li>Very small and unimportant effects can turn out to be statistically significant if the sample size is large enough.</li>
</ul>
<p><strong>Insignificant result</strong></p>
<ul>
<li>If the probability of the effect occurring by chance is large (greater than .05), the alternative hypothesis is rejected. However, this does not mean that the null hypothesis is true.</li>
<li>Although an effect might not be large enough to be anything other than a chance finding, it doesn’t mean that the effect is zero.</li>
<li>In fact, two random samples will always have slightly different means that would deemed to be statistically significant if the samples were large enough.</li>
</ul>
<p>Thus, you should not base your research conclusion on p-values alone!</p>
<p>It is also crucial to <strong>determine the sample size before you run the experiment</strong> or before you start your analysis. Why? Consider the following example:</p>
<ul>
<li>You run an experiment</li>
<li>After each respondent you analyze the data and look at the mean difference between the two groups with a t-test</li>
<li>You stop when you have a significant effect</li>
</ul>
<p>This is called p-hacking and should be avoided at all costs. Assuming that both groups come from the same population (i.e., there is <strong>no difference</strong> in the means): What is the likelihood that the result will be significant at some point? In other words, what is the likelihood that you will draw the wrong conclusion from your data that there is an effect, while there is none? This is shown in the following graph using simulated data - the color red indicates significant test results that arise although there is no effect (i.e., false positives).</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-175"></span>
<img src="_main_files/figure-html/unnamed-chunk-175-1.png" alt="p-hacking (red indicates false positives)" width="672" />
<p class="caption">
Figure 6.1: p-hacking (red indicates false positives)
</p>
</div>

</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="correlation.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="anova.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
